//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134295.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Account
    {
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Mat Khau")]
        [DataType(DataType.Password)]
        public string MK { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Nhap lai mat Khau")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("MK", ErrorMessage = "Mat khau khong khop, nhap lai !")]
        public string RePass { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Ten hien thi")]

        public string TenHienThi { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
